//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoticApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BODEGA
    {
        public decimal ID_BODEGA { get; set; }
        public Nullable<decimal> ID_FARMACIA { get; set; }
        public Nullable<decimal> ID_MEDICAMENTO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> VALOR_UNITARIO { get; set; }
    
        public virtual FARMACIA FARMACIA { get; set; }
        public virtual MEDICAMENTO MEDICAMENTO { get; set; }
    }
}
