//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoticApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class boticaapEntities1 : DbContext
    {
        public boticaapEntities1()
            : base("name=boticaapEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BODEGA> BODEGA { get; set; }
        public virtual DbSet<FARMACIA> FARMACIA { get; set; }
        public virtual DbSet<MEDICAMENTO> MEDICAMENTO { get; set; }
        public virtual DbSet<MEDICAMENTO_TIPO> MEDICAMENTO_TIPO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
