//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoticApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public decimal ID_USUARIO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string EMAIL { get; set; }
        public string USUARIO1 { get; set; }
        public string CLAVE { get; set; }
        public string ESFARMACIA { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public Nullable<decimal> NIT { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    }
}
